---
deployment:
  tasks:
    - export DEPLOYPATH=/home/guruxjxh/melodiahomecare.gurucompetitions.com/
    - /bin/cp * $DEPLOYPATH
    -/bin/cp/css/ * $DEPLOYPATH
    -/bin/cp/js/ * $DEPLOYPATH
    -/bin/cp/images/ * $DEPLOYPATH